### ISSUE TITLE
Order processing system with tracking

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#263]
As a MiBi-Portal admin I need an order processing system (inspired by parcel services). Date and time for all of the following steps should be saved:
- [ ] An new page displays all orders and their progress: Admin view for all orders, with user names
- [ ] An new page displays all orders and their progress: Admin view for all orders, user view with user's orders
- [ ] Having logged in into MiBi-Portal a Probeneinsendebogen is uploaded: An Order number is created and for every data set (for every row) an ID is created.
- [ ] If the Probeneinsendebogen is edited online, this is tracked (like a Code diff on GitHub)
- [ ] When the Probeneinsendebogen is sent to BfR via the MiBi-Portal this is stated in the order
- [ ] When a LIMS order has been found by the MiBi-Portal the LIMS order number is stated in the order (connection to LIMS). 
- [ ] When BfR results are found in LIMS they are added to the order.
- [ ] When BfR results for all samples of an order are available the order is completed and will be closed (no edits possible at all). This is indicated on the order page by changing the background colour of the order row... or with a symbol

**Comment by afalenski** [comment]
Not necessary.
