### ISSUE TITLE
Create browser data table

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#349]
As a user I would like to see the data submitted as Probeneinsendebogen Excel sheet or as JSON file in the browser as a table.

- [x] The table has 21 columns. The first column contains a row number starting with 1 (integer), the second shows the NRL according to the pathogen in column 5 and columns 3-21 contain uploaded data. In large datasets a vertical scroll bar appears on the right and the table headers are fixed when scrolling down. *5EP*
- [x] Column width adapts to browser window width until 1100px width; for narrower browser windows a horizontal scrollbar appears. Text in columns adapts to column width (line break). *2EP*
- [x] The table shows errors (if applicable) after data was uploaded or when clicking on "validieren". If there are errors in the data the browser table displays colours for errors (red), warnings (yellow) and auto-corrections (blue). *2EP*
- [x] Errors, warnings and auto-corrections are explained in speech bubbles (text from error code table) when hovering with the mouse over a coloured cell. *3EP*
- [x] When double clicking into a cell the text can be edited (columns 3-21). *3EP*
- [x] If a pathogen (column 5) is erroneous and if the text recognition finds possible alternative pathogen texts (from ADV catalog no 16 or from an additional pathogen list) the pathogen cell displays a white dropdown symbol. Clicking on this a dropdown list displays up to 20 suggestions for pathogens. The text in the cell can still be edited. *3EP*
![mpc349_pathogen-correction-suggestions.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/a24bbcfb-959d-4a84-bf1d-818348f4e0e5)
- [x] A single click on a cell highlights it (blue borders). *2EP*
- [ ] The content of a cell can be copied to another cell: Highlight cell, press Ctrl+C, click on another cell, press Ctrl+V. *3EP*
- - - - - - - - -
- [ ] It is possible to highlight several cells in a row and copy them to another row. *5EP*
