### ISSUE TITLE
Client Refactoring

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#421]
As a developer i would like to add new features easy, fast and bug free to the client. To do so the client has to be refactored so that the code reflects our common coding best practices.

- [ ] Refactor upload components: The component structure is to complicated for the purpose, also app logic like the close warning is handled in the upload component but should handled in the upload effect.
- [ ] Refactor samples state: Should be in a separate sub feature, also imported and validated data should be handled in a more separate way to prevent working with derived states.
- [ ] Use navigation service instead directly using the router to navigate, handle navigations errors in a meaningful way
